server:
  port: 7000

spring:
  application:
    name: user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: ${DATABASE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    url: ${DATABASE_URL:jdbc:mysql://localhost:33306/user_ddd_pattern?createDatabaseIfNotExist=true&characterEncoding=utf8&collation=utf8_unicode_ci}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}
    hikari:
      pool-name: ServicePool
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      transaction-isolation: TRANSACTION_READ_COMMITTED

  main:
    banner-mode: off
  flyway:
    enabled: false
  logging:
    level:
      org:
        springframework:
          security=DEBUG:
